name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v2
    - name: Configure
    - run: brew install nasm
    - name: make KripayaOS.bin
      run: make KripayaOS.bin
