name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - name: Set up NASM
    - uses: ilammy/setup-nasm@v1.2.0
    - uses: actions/checkout@v2
    - name: make KripayaOS.bin
      run: make KripayaOS.bin
