name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  steps:
    - uses: actions/checkout@v1
    - name: Configure
      run: brew install nasm i386-elf-binutils i386-elf-gcc i386-elf-gdb
    - name: Build the OS
      run: make KripayaOS.bin

